### PR TITLE
css-positioning -James Aguirre

### PR DESCRIPTION
**Pull request by james-aguirre**
Screenshot 2023-03-31 at 9 50 35 AM

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Please include screenshots of the other 2 files as well please

**Comment by james-aguirre** [comment]
Screenshot 2023-03-31 at 10 22 01 AM
Screenshot 2023-03-31 at 10 22 09 AM
My bad! I'll include all screenshots in the future @shawnkost

**Review by shawnkost — CHANGES_REQUESTED** [review]
`absolute.html` doesn't quite look like our example image. The emoji should be in the top right, and the text in the bottom center.

**Comment by james-aguirre** [comment]
Screenshot 2023-04-03 at 11 07 16 AM

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
